version: '3'
services:
  nginx-f2ban-web:
    build: ./nginx/
    name: nginx-f2ban-web
    read_only: true
    ports:
      - 8000:80

  app-f2ban-web:
    build: ./app/
    name: app-f2ban-web
    read_only: true
    ports:
      - 8000:80

