version: '3'
services:
  nginx-f2ban-web:
    build: ./nginx/
    container_name: nginx-f2ban-web
    read_only: true
    restart: always
    ports:
    #  - 8000:80
      - 8443:443
    volumes:
      - ./data/nginx/log/:/var/log/nginx/

  app-f2ban-web:
    build: ./app/
    container_name: app-f2ban-web
    read_only: true
    restart: always
    # For debug only, it should be commented later
    #ports:
    #  - 127.0.0.1:5000:5000
    volumes:
        - /var/lib/fail2ban/fail2ban.sqlite3:/var/lib/fail2ban/fail2ban.sqlite3

